GCC = g++
RM = rm
LN = ln
FLIBS = -llapack -lblas
FFLAGS = -c -g -Wall -std=c++11
FFLAGSOPT = -O3 -fopenmp
DISLIN_INC = /usr/local/dislin/df/real64


all:
	$(MAKE) exo_1

exo_1:
	$(GCC) $(FFLAGS) exo_1.cpp 
	$(GCC) -o exo_1 exo_1.o
	
cl_exo_1:
	$(RM) exo_1.o exo_1
	
exo_2:
	$(GCC) $(FFLAGS) exo_2.cpp 
	$(GCC) -o exo_2 exo_2.o
	
cl_exo_2:
	$(RM) exo_2.o exo_2
	
exo_3:
	$(GCC) $(FFLAGS) exo_3.cpp 
	$(GCC) -o exo_3 exo_3.o
	
cl_exo_3:
	$(RM) exo_3.o exo_3
	
exo_4:
	$(GCC) $(FFLAGS) exo_4.cpp 
	$(GCC) -o exo_4 exo_4.o
	
cl_exo_4:
	$(RM) exo_4.o exo_4
	
exo_5:
	$(GCC) $(FFLAGS) exo_5.cpp 
	$(GCC) -o exo_5 exo_5.o
	
cl_exo_5:
	$(RM) exo_5.o exo_5

exo_6:
	$(GCC) $(FFLAGS) exo_6.cpp 
	$(GCC) -o exo_6 exo_6.o
	
cl_exo_6:
	$(RM) exo_6.o exo_6
	
exo_7:
	$(GCC) $(FFLAGS) exo_7.cpp 
	$(GCC) -o exo_7 exo_7.o
	
cl_exo_7:
	$(RM) exo_7.o exo_7
	
exo_8:
	$(GCC) $(FFLAGS) exo_8.cpp 
	$(GCC) -o exo_8 exo_8.o
	
cl_exo_8:
	$(RM) exo_8.o exo_8
	
exo_9:
	$(GCC) $(FFLAGS) -fopenmp exo_9.cpp 
	$(GCC) -fopenmp -o exo_9 exo_9.o
	
cl_exo_9:
	$(RM) exo_9.o exo_9

exo_10:
	$(GCC) $(FFLAGS) -fopenmp exo_10.cpp 
	$(GCC) -fopenmp -o exo_10 exo_10.o
	
cl_exo_10:
	$(RM) exo_10.o exo_10

exo_11:
	$(GCC) $(FFLAGS) -fopenmp exo_11.cpp 
	$(GCC) -fopenmp -o exo_11 exo_11.o
	
cl_exo_11:
	$(RM) exo_11.o exo_11
