// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cf_diff_solv_euls
List cf_diff_solv_euls(const Eigen::MatrixXd& alpha, const Eigen::VectorXd& I, const Eigen::VectorXd& A, const Eigen::VectorXd& B, const Eigen::VectorXd& t, const Eigen::VectorXd& x);
RcppExport SEXP _CFINI_cf_diff_solv_euls(SEXP alphaSEXP, SEXP ISEXP, SEXP ASEXP, SEXP BSEXP, SEXP tSEXP, SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type I(ISEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type B(BSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type t(tSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cf_diff_solv_euls(alpha, I, A, B, t, x));
    return rcpp_result_gen;
END_RCPP
}
// cf_diff_solv_cns
List cf_diff_solv_cns(const double& theta, const Eigen::MatrixXd& alpha, const Eigen::VectorXd& I, const Eigen::VectorXd& A, const Eigen::VectorXd& B, const Eigen::VectorXd& t, const Eigen::VectorXd& x);
RcppExport SEXP _CFINI_cf_diff_solv_cns(SEXP thetaSEXP, SEXP alphaSEXP, SEXP ISEXP, SEXP ASEXP, SEXP BSEXP, SEXP tSEXP, SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type I(ISEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type B(BSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type t(tSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cf_diff_solv_cns(theta, alpha, I, A, B, t, x));
    return rcpp_result_gen;
END_RCPP
}
// cf_black_scholes_solv_cns
List cf_black_scholes_solv_cns(const double& sigma, const double& rate, const double& theta, const Eigen::VectorXd& I, const Eigen::VectorXd& A, const Eigen::VectorXd& B, const Eigen::VectorXd& t, const Eigen::VectorXd& x);
RcppExport SEXP _CFINI_cf_black_scholes_solv_cns(SEXP sigmaSEXP, SEXP rateSEXP, SEXP thetaSEXP, SEXP ISEXP, SEXP ASEXP, SEXP BSEXP, SEXP tSEXP, SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double& >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< const double& >::type rate(rateSEXP);
    Rcpp::traits::input_parameter< const double& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type I(ISEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type B(BSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type t(tSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cf_black_scholes_solv_cns(sigma, rate, theta, I, A, B, t, x));
    return rcpp_result_gen;
END_RCPP
}
// cf_uniform_grid
Eigen::VectorXd cf_uniform_grid(const double& a, const double& b, const double& N);
RcppExport SEXP _CFINI_cf_uniform_grid(SEXP aSEXP, SEXP bSEXP, SEXP NSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const double& >::type b(bSEXP);
    Rcpp::traits::input_parameter< const double& >::type N(NSEXP);
    rcpp_result_gen = Rcpp::wrap(cf_uniform_grid(a, b, N));
    return rcpp_result_gen;
END_RCPP
}
// cf_adapt_grid
Eigen::VectorXd cf_adapt_grid(const double& l, const double& a, const double& b, const double& N, const double& E);
RcppExport SEXP _CFINI_cf_adapt_grid(SEXP lSEXP, SEXP aSEXP, SEXP bSEXP, SEXP NSEXP, SEXP ESEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double& >::type l(lSEXP);
    Rcpp::traits::input_parameter< const double& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const double& >::type b(bSEXP);
    Rcpp::traits::input_parameter< const double& >::type N(NSEXP);
    Rcpp::traits::input_parameter< const double& >::type E(ESEXP);
    rcpp_result_gen = Rcpp::wrap(cf_adapt_grid(l, a, b, N, E));
    return rcpp_result_gen;
END_RCPP
}
// cf_tri_diag_solv
void cf_tri_diag_solv(Eigen::VectorXd& a, Eigen::VectorXd& b, Eigen::VectorXd& c, Eigen::VectorXd& d);
RcppExport SEXP _CFINI_cf_tri_diag_solv(SEXP aSEXP, SEXP bSEXP, SEXP cSEXP, SEXP dSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::VectorXd& >::type a(aSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd& >::type b(bSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd& >::type c(cSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd& >::type d(dSEXP);
    cf_tri_diag_solv(a, b, c, d);
    return R_NilValue;
END_RCPP
}
// cf_wiener
Eigen::MatrixXd cf_wiener(const int& d, const Eigen::VectorXd& t);
RcppExport SEXP _CFINI_cf_wiener(SEXP dSEXP, SEXP tSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int& >::type d(dSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type t(tSEXP);
    rcpp_result_gen = Rcpp::wrap(cf_wiener(d, t));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_CFINI_cf_diff_solv_euls", (DL_FUNC) &_CFINI_cf_diff_solv_euls, 6},
    {"_CFINI_cf_diff_solv_cns", (DL_FUNC) &_CFINI_cf_diff_solv_cns, 7},
    {"_CFINI_cf_black_scholes_solv_cns", (DL_FUNC) &_CFINI_cf_black_scholes_solv_cns, 8},
    {"_CFINI_cf_uniform_grid", (DL_FUNC) &_CFINI_cf_uniform_grid, 3},
    {"_CFINI_cf_adapt_grid", (DL_FUNC) &_CFINI_cf_adapt_grid, 5},
    {"_CFINI_cf_tri_diag_solv", (DL_FUNC) &_CFINI_cf_tri_diag_solv, 4},
    {"_CFINI_cf_wiener", (DL_FUNC) &_CFINI_cf_wiener, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_CFINI(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
