# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

GridEngine <- function(a, b, N) {
    .Call('_CFINI_GridEngine', PACKAGE = 'CFINI', a, b, N)
}

DiffusionSolver <- function(alpha, I, A, B, t0, t1, Nt, x0, x1, Nx) {
    .Call('_CFINI_DiffusionSolver', PACKAGE = 'CFINI', alpha, I, A, B, t0, t1, Nt, x0, x1, Nx)
}

