# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Diffusion solver
#' @description Solver for standard diffusion problems
#' @param alpha
#' @param I
#' @param A
#' @param B
#' @param t
#' @param x
#' @return List with solution parameters
#' @note Diffusion solver for pricing options
#' @author Pedro Guarderas
#' @export
CFDiffSolvES <- function(alpha, I, A, B, t, x) {
    .Call('_CFINI_CFDiffSolvES', PACKAGE = 'CFINI', alpha, I, A, B, t, x)
}

#' @title Diffusion solver
#' @description Solver for diffusion problems implemented with Crank-Nicolson scheme
#' @param alpha
#' @param theta
#' @param I
#' @param A
#' @param B
#' @param t
#' @param x
#' @return List with solution parameters
#' @note Diffusion solver for pricing options
#' @author Pedro Guarderas
#' @export
CFDiffSolvCNS <- function(alpha, theta, I, A, B, t, x) {
    .Call('_CFINI_CFDiffSolvCNS', PACKAGE = 'CFINI', alpha, theta, I, A, B, t, x)
}

#' @title Black-Scholes solver
#' @description Solver for Black-Scholes models implemented with Crank-Nicolson scheme
#' @param sigma
#' @param rate
#' @param theta
#' @param I
#' @param A
#' @param B
#' @param t
#' @param x
#' @return List with solution parameters
#' @note pricing options
#' @author Pedro Guarderas
#' @export
CFBlackScholesSolvCNS <- function(sigma, rate, theta, I, A, B, t, x) {
    .Call('_CFINI_CFBlackScholesSolvCNS', PACKAGE = 'CFINI', sigma, rate, theta, I, A, B, t, x)
}

GridUniform <- function(a, b, N) {
    .Call('_CFINI_GridUniform', PACKAGE = 'CFINI', a, b, N)
}

GridExpAddapt <- function(l, a, b, N, E) {
    .Call('_CFINI_GridExpAddapt', PACKAGE = 'CFINI', l, a, b, N, E)
}

CFTriDiagSolv <- function(a, b, c, d) {
    invisible(.Call('_CFINI_CFTriDiagSolv', PACKAGE = 'CFINI', a, b, c, d))
}

